USE [master]
GO

/****** Object:  Database [garajauto]    Script Date: 12/19/2017 8:26:44 AM ******/
DROP DATABASE [garajauto]
GO

/****** Object:  Database [garajauto]    Script Date: 12/19/2017 8:26:44 AM ******/
CREATE DATABASE [garajauto]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'garajauto', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\garajauto.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'garajauto_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\garajauto_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [garajauto] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [garajauto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [garajauto] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [garajauto] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [garajauto] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [garajauto] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [garajauto] SET ARITHABORT OFF 
GO

ALTER DATABASE [garajauto] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [garajauto] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [garajauto] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [garajauto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [garajauto] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [garajauto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [garajauto] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [garajauto] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [garajauto] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [garajauto] SET  DISABLE_BROKER 
GO

ALTER DATABASE [garajauto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [garajauto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [garajauto] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [garajauto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [garajauto] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [garajauto] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [garajauto] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [garajauto] SET RECOVERY FULL 
GO

ALTER DATABASE [garajauto] SET  MULTI_USER 
GO

ALTER DATABASE [garajauto] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [garajauto] SET DB_CHAINING OFF 
GO

ALTER DATABASE [garajauto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [garajauto] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [garajauto] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [garajauto] SET QUERY_STORE = OFF
GO

USE [garajauto]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [garajauto] SET  READ_WRITE 
GO

