#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomWorks
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="garajauto")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbrevet_dispozitiv(brevet_dispozitiv instance);
    partial void Updatebrevet_dispozitiv(brevet_dispozitiv instance);
    partial void Deletebrevet_dispozitiv(brevet_dispozitiv instance);
    partial void Insertvanzator(vanzator instance);
    partial void Updatevanzator(vanzator instance);
    partial void Deletevanzator(vanzator instance);
    partial void Insertdirector_tehnic(director_tehnic instance);
    partial void Updatedirector_tehnic(director_tehnic instance);
    partial void Deletedirector_tehnic(director_tehnic instance);
    partial void Insertdispozitiv(dispozitiv instance);
    partial void Updatedispozitiv(dispozitiv instance);
    partial void Deletedispozitiv(dispozitiv instance);
    partial void Insertfabricant(fabricant instance);
    partial void Updatefabricant(fabricant instance);
    partial void Deletefabricant(fabricant instance);
    partial void Insertmasina(masina instance);
    partial void Updatemasina(masina instance);
    partial void Deletemasina(masina instance);
    partial void Insertmecanic(mecanic instance);
    partial void Updatemecanic(mecanic instance);
    partial void Deletemecanic(mecanic instance);
    partial void Insertoperatie(operatie instance);
    partial void Updateoperatie(operatie instance);
    partial void Deleteoperatie(operatie instance);
    partial void Insertpiesa(piesa instance);
    partial void Updatepiesa(piesa instance);
    partial void Deletepiesa(piesa instance);
    partial void Insertproprietar(proprietar instance);
    partial void Updateproprietar(proprietar instance);
    partial void Deleteproprietar(proprietar instance);
    partial void Insertreparatie(reparatie instance);
    partial void Updatereparatie(reparatie instance);
    partial void Deletereparatie(reparatie instance);
    partial void Insertsupplier(supplier instance);
    partial void Updatesupplier(supplier instance);
    partial void Deletesupplier(supplier instance);
    partial void Inserttip(tip instance);
    partial void Updatetip(tip instance);
    partial void Deletetip(tip instance);
    partial void Inserttip_brevet(tip_brevet instance);
    partial void Updatetip_brevet(tip_brevet instance);
    partial void Deletetip_brevet(tip_brevet instance);
    partial void Insertutilizare_dispozitiv(utilizare_dispozitiv instance);
    partial void Updateutilizare_dispozitiv(utilizare_dispozitiv instance);
    partial void Deleteutilizare_dispozitiv(utilizare_dispozitiv instance);
    partial void Insertvanzare(vanzare instance);
    partial void Updatevanzare(vanzare instance);
    partial void Deletevanzare(vanzare instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CustomWorks.Properties.Settings.Default.garajautoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<brevet_dispozitiv> brevet_dispozitivs
		{
			get
			{
				return this.GetTable<brevet_dispozitiv>();
			}
		}
		
		public System.Data.Linq.Table<vanzator> vanzators
		{
			get
			{
				return this.GetTable<vanzator>();
			}
		}
		
		public System.Data.Linq.Table<director_tehnic> director_tehnics
		{
			get
			{
				return this.GetTable<director_tehnic>();
			}
		}
		
		public System.Data.Linq.Table<dispozitiv> dispozitivs
		{
			get
			{
				return this.GetTable<dispozitiv>();
			}
		}
		
		public System.Data.Linq.Table<fabricant> fabricants
		{
			get
			{
				return this.GetTable<fabricant>();
			}
		}
		
		public System.Data.Linq.Table<masina> masinas
		{
			get
			{
				return this.GetTable<masina>();
			}
		}
		
		public System.Data.Linq.Table<mecanic> mecanics
		{
			get
			{
				return this.GetTable<mecanic>();
			}
		}
		
		public System.Data.Linq.Table<operatie> operaties
		{
			get
			{
				return this.GetTable<operatie>();
			}
		}
		
		public System.Data.Linq.Table<piesa> piesas
		{
			get
			{
				return this.GetTable<piesa>();
			}
		}
		
		public System.Data.Linq.Table<proprietar> proprietars
		{
			get
			{
				return this.GetTable<proprietar>();
			}
		}
		
		public System.Data.Linq.Table<reparatie> reparaties
		{
			get
			{
				return this.GetTable<reparatie>();
			}
		}
		
		public System.Data.Linq.Table<supplier> suppliers
		{
			get
			{
				return this.GetTable<supplier>();
			}
		}
		
		public System.Data.Linq.Table<tip> tips
		{
			get
			{
				return this.GetTable<tip>();
			}
		}
		
		public System.Data.Linq.Table<tip_brevet> tip_brevets
		{
			get
			{
				return this.GetTable<tip_brevet>();
			}
		}
		
		public System.Data.Linq.Table<utilizare_dispozitiv> utilizare_dispozitivs
		{
			get
			{
				return this.GetTable<utilizare_dispozitiv>();
			}
		}
		
		public System.Data.Linq.Table<vanzare> vanzares
		{
			get
			{
				return this.GetTable<vanzare>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.brevet_dispozitiv")]
	public partial class brevet_dispozitiv : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _fk_mecanic;
		
		private int _tipbrevet;
		
		private EntityRef<mecanic> _mecanic;
		
		private EntityRef<tip_brevet> _tip_brevet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onfk_mecanicChanging(int value);
    partial void Onfk_mecanicChanged();
    partial void OntipbrevetChanging(int value);
    partial void OntipbrevetChanged();
    #endregion
		
		public brevet_dispozitiv()
		{
			this._mecanic = default(EntityRef<mecanic>);
			this._tip_brevet = default(EntityRef<tip_brevet>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_mecanic", DbType="Int NOT NULL")]
		public int fk_mecanic
		{
			get
			{
				return this._fk_mecanic;
			}
			set
			{
				if ((this._fk_mecanic != value))
				{
					if (this._mecanic.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_mecanicChanging(value);
					this.SendPropertyChanging();
					this._fk_mecanic = value;
					this.SendPropertyChanged("fk_mecanic");
					this.Onfk_mecanicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipbrevet", DbType="Int NOT NULL")]
		public int tipbrevet
		{
			get
			{
				return this._tipbrevet;
			}
			set
			{
				if ((this._tipbrevet != value))
				{
					if (this._tip_brevet.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntipbrevetChanging(value);
					this.SendPropertyChanging();
					this._tipbrevet = value;
					this.SendPropertyChanged("tipbrevet");
					this.OntipbrevetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mecanic_brevet_dispozitiv", Storage="_mecanic", ThisKey="fk_mecanic", OtherKey="id", IsForeignKey=true)]
		public mecanic mecanic
		{
			get
			{
				return this._mecanic.Entity;
			}
			set
			{
				mecanic previousValue = this._mecanic.Entity;
				if (((previousValue != value) 
							|| (this._mecanic.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mecanic.Entity = null;
						previousValue.brevet_dispozitivs.Remove(this);
					}
					this._mecanic.Entity = value;
					if ((value != null))
					{
						value.brevet_dispozitivs.Add(this);
						this._fk_mecanic = value.id;
					}
					else
					{
						this._fk_mecanic = default(int);
					}
					this.SendPropertyChanged("mecanic");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tip_brevet_brevet_dispozitiv", Storage="_tip_brevet", ThisKey="tipbrevet", OtherKey="id", IsForeignKey=true)]
		public tip_brevet tip_brevet
		{
			get
			{
				return this._tip_brevet.Entity;
			}
			set
			{
				tip_brevet previousValue = this._tip_brevet.Entity;
				if (((previousValue != value) 
							|| (this._tip_brevet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tip_brevet.Entity = null;
						previousValue.brevet_dispozitivs.Remove(this);
					}
					this._tip_brevet.Entity = value;
					if ((value != null))
					{
						value.brevet_dispozitivs.Add(this);
						this._tipbrevet = value.id;
					}
					else
					{
						this._tipbrevet = default(int);
					}
					this.SendPropertyChanged("tip_brevet");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vanzator")]
	public partial class vanzator : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nume;
		
		private string _prenume;
		
		private System.DateTime _data_angajarii;
		
		private decimal _salariu;
		
		private System.Nullable<int> _fk_director_tehnic;
		
		private EntitySet<vanzare> _vanzares;
		
		private EntityRef<director_tehnic> _director_tehnic;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnumeChanging(string value);
    partial void OnnumeChanged();
    partial void OnprenumeChanging(string value);
    partial void OnprenumeChanged();
    partial void Ondata_angajariiChanging(System.DateTime value);
    partial void Ondata_angajariiChanged();
    partial void OnsalariuChanging(decimal value);
    partial void OnsalariuChanged();
    partial void Onfk_director_tehnicChanging(System.Nullable<int> value);
    partial void Onfk_director_tehnicChanged();
    #endregion
		
		public vanzator()
		{
			this._vanzares = new EntitySet<vanzare>(new Action<vanzare>(this.attach_vanzares), new Action<vanzare>(this.detach_vanzares));
			this._director_tehnic = default(EntityRef<director_tehnic>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nume", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string nume
		{
			get
			{
				return this._nume;
			}
			set
			{
				if ((this._nume != value))
				{
					this.OnnumeChanging(value);
					this.SendPropertyChanging();
					this._nume = value;
					this.SendPropertyChanged("nume");
					this.OnnumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenume", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string prenume
		{
			get
			{
				return this._prenume;
			}
			set
			{
				if ((this._prenume != value))
				{
					this.OnprenumeChanging(value);
					this.SendPropertyChanging();
					this._prenume = value;
					this.SendPropertyChanged("prenume");
					this.OnprenumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_angajarii", DbType="Date NOT NULL")]
		public System.DateTime data_angajarii
		{
			get
			{
				return this._data_angajarii;
			}
			set
			{
				if ((this._data_angajarii != value))
				{
					this.Ondata_angajariiChanging(value);
					this.SendPropertyChanging();
					this._data_angajarii = value;
					this.SendPropertyChanged("data_angajarii");
					this.Ondata_angajariiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salariu", DbType="Money NOT NULL")]
		public decimal salariu
		{
			get
			{
				return this._salariu;
			}
			set
			{
				if ((this._salariu != value))
				{
					this.OnsalariuChanging(value);
					this.SendPropertyChanging();
					this._salariu = value;
					this.SendPropertyChanged("salariu");
					this.OnsalariuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_director_tehnic", DbType="Int")]
		public System.Nullable<int> fk_director_tehnic
		{
			get
			{
				return this._fk_director_tehnic;
			}
			set
			{
				if ((this._fk_director_tehnic != value))
				{
					if (this._director_tehnic.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_director_tehnicChanging(value);
					this.SendPropertyChanging();
					this._fk_director_tehnic = value;
					this.SendPropertyChanged("fk_director_tehnic");
					this.Onfk_director_tehnicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vanzator_vanzare", Storage="_vanzares", ThisKey="id", OtherKey="fk_angajat")]
		public EntitySet<vanzare> vanzares
		{
			get
			{
				return this._vanzares;
			}
			set
			{
				this._vanzares.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="director_tehnic_vanzator", Storage="_director_tehnic", ThisKey="fk_director_tehnic", OtherKey="id", IsForeignKey=true)]
		public director_tehnic director_tehnic
		{
			get
			{
				return this._director_tehnic.Entity;
			}
			set
			{
				director_tehnic previousValue = this._director_tehnic.Entity;
				if (((previousValue != value) 
							|| (this._director_tehnic.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._director_tehnic.Entity = null;
						previousValue.vanzators.Remove(this);
					}
					this._director_tehnic.Entity = value;
					if ((value != null))
					{
						value.vanzators.Add(this);
						this._fk_director_tehnic = value.id;
					}
					else
					{
						this._fk_director_tehnic = default(Nullable<int>);
					}
					this.SendPropertyChanged("director_tehnic");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_vanzares(vanzare entity)
		{
			this.SendPropertyChanging();
			entity.vanzator = this;
		}
		
		private void detach_vanzares(vanzare entity)
		{
			this.SendPropertyChanging();
			entity.vanzator = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.director_tehnic")]
	public partial class director_tehnic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nume;
		
		private string _prenume;
		
		private int _salariu;
		
		private System.DateTime _data_angajarii;
		
		private EntitySet<vanzator> _vanzators;
		
		private EntitySet<mecanic> _mecanics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnumeChanging(string value);
    partial void OnnumeChanged();
    partial void OnprenumeChanging(string value);
    partial void OnprenumeChanged();
    partial void OnsalariuChanging(int value);
    partial void OnsalariuChanged();
    partial void Ondata_angajariiChanging(System.DateTime value);
    partial void Ondata_angajariiChanged();
    #endregion
		
		public director_tehnic()
		{
			this._vanzators = new EntitySet<vanzator>(new Action<vanzator>(this.attach_vanzators), new Action<vanzator>(this.detach_vanzators));
			this._mecanics = new EntitySet<mecanic>(new Action<mecanic>(this.attach_mecanics), new Action<mecanic>(this.detach_mecanics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nume", DbType="NChar(130) NOT NULL", CanBeNull=false)]
		public string nume
		{
			get
			{
				return this._nume;
			}
			set
			{
				if ((this._nume != value))
				{
					this.OnnumeChanging(value);
					this.SendPropertyChanging();
					this._nume = value;
					this.SendPropertyChanged("nume");
					this.OnnumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenume", DbType="NChar(130) NOT NULL", CanBeNull=false)]
		public string prenume
		{
			get
			{
				return this._prenume;
			}
			set
			{
				if ((this._prenume != value))
				{
					this.OnprenumeChanging(value);
					this.SendPropertyChanging();
					this._prenume = value;
					this.SendPropertyChanged("prenume");
					this.OnprenumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salariu", DbType="Int NOT NULL")]
		public int salariu
		{
			get
			{
				return this._salariu;
			}
			set
			{
				if ((this._salariu != value))
				{
					this.OnsalariuChanging(value);
					this.SendPropertyChanging();
					this._salariu = value;
					this.SendPropertyChanged("salariu");
					this.OnsalariuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_angajarii", DbType="Date NOT NULL")]
		public System.DateTime data_angajarii
		{
			get
			{
				return this._data_angajarii;
			}
			set
			{
				if ((this._data_angajarii != value))
				{
					this.Ondata_angajariiChanging(value);
					this.SendPropertyChanging();
					this._data_angajarii = value;
					this.SendPropertyChanged("data_angajarii");
					this.Ondata_angajariiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="director_tehnic_vanzator", Storage="_vanzators", ThisKey="id", OtherKey="fk_director_tehnic")]
		public EntitySet<vanzator> vanzators
		{
			get
			{
				return this._vanzators;
			}
			set
			{
				this._vanzators.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="director_tehnic_mecanic", Storage="_mecanics", ThisKey="id", OtherKey="fk_director")]
		public EntitySet<mecanic> mecanics
		{
			get
			{
				return this._mecanics;
			}
			set
			{
				this._mecanics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_vanzators(vanzator entity)
		{
			this.SendPropertyChanging();
			entity.director_tehnic = this;
		}
		
		private void detach_vanzators(vanzator entity)
		{
			this.SendPropertyChanging();
			entity.director_tehnic = null;
		}
		
		private void attach_mecanics(mecanic entity)
		{
			this.SendPropertyChanging();
			entity.director_tehnic = this;
		}
		
		private void detach_mecanics(mecanic entity)
		{
			this.SendPropertyChanging();
			entity.director_tehnic = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dispozitiv")]
	public partial class dispozitiv : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _brevet_necesar;
		
		private string _nume;
		
		private EntitySet<utilizare_dispozitiv> _utilizare_dispozitivs;
		
		private EntityRef<tip_brevet> _tip_brevet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onbrevet_necesarChanging(int value);
    partial void Onbrevet_necesarChanged();
    partial void OnnumeChanging(string value);
    partial void OnnumeChanged();
    #endregion
		
		public dispozitiv()
		{
			this._utilizare_dispozitivs = new EntitySet<utilizare_dispozitiv>(new Action<utilizare_dispozitiv>(this.attach_utilizare_dispozitivs), new Action<utilizare_dispozitiv>(this.detach_utilizare_dispozitivs));
			this._tip_brevet = default(EntityRef<tip_brevet>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brevet_necesar", DbType="Int NOT NULL")]
		public int brevet_necesar
		{
			get
			{
				return this._brevet_necesar;
			}
			set
			{
				if ((this._brevet_necesar != value))
				{
					if (this._tip_brevet.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onbrevet_necesarChanging(value);
					this.SendPropertyChanging();
					this._brevet_necesar = value;
					this.SendPropertyChanged("brevet_necesar");
					this.Onbrevet_necesarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nume", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string nume
		{
			get
			{
				return this._nume;
			}
			set
			{
				if ((this._nume != value))
				{
					this.OnnumeChanging(value);
					this.SendPropertyChanging();
					this._nume = value;
					this.SendPropertyChanged("nume");
					this.OnnumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dispozitiv_utilizare_dispozitiv", Storage="_utilizare_dispozitivs", ThisKey="id", OtherKey="fk_dispozitiv")]
		public EntitySet<utilizare_dispozitiv> utilizare_dispozitivs
		{
			get
			{
				return this._utilizare_dispozitivs;
			}
			set
			{
				this._utilizare_dispozitivs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tip_brevet_dispozitiv", Storage="_tip_brevet", ThisKey="brevet_necesar", OtherKey="id", IsForeignKey=true)]
		public tip_brevet tip_brevet
		{
			get
			{
				return this._tip_brevet.Entity;
			}
			set
			{
				tip_brevet previousValue = this._tip_brevet.Entity;
				if (((previousValue != value) 
							|| (this._tip_brevet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tip_brevet.Entity = null;
						previousValue.dispozitivs.Remove(this);
					}
					this._tip_brevet.Entity = value;
					if ((value != null))
					{
						value.dispozitivs.Add(this);
						this._brevet_necesar = value.id;
					}
					else
					{
						this._brevet_necesar = default(int);
					}
					this.SendPropertyChanged("tip_brevet");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_utilizare_dispozitivs(utilizare_dispozitiv entity)
		{
			this.SendPropertyChanging();
			entity.dispozitiv = this;
		}
		
		private void detach_utilizare_dispozitivs(utilizare_dispozitiv entity)
		{
			this.SendPropertyChanging();
			entity.dispozitiv = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fabricant")]
	public partial class fabricant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nume;
		
		private string _nr_telefon;
		
		private EntitySet<masina> _masinas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnumeChanging(string value);
    partial void OnnumeChanged();
    partial void Onnr_telefonChanging(string value);
    partial void Onnr_telefonChanged();
    #endregion
		
		public fabricant()
		{
			this._masinas = new EntitySet<masina>(new Action<masina>(this.attach_masinas), new Action<masina>(this.detach_masinas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nume", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string nume
		{
			get
			{
				return this._nume;
			}
			set
			{
				if ((this._nume != value))
				{
					this.OnnumeChanging(value);
					this.SendPropertyChanging();
					this._nume = value;
					this.SendPropertyChanged("nume");
					this.OnnumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_telefon", DbType="NChar(10)")]
		public string nr_telefon
		{
			get
			{
				return this._nr_telefon;
			}
			set
			{
				if ((this._nr_telefon != value))
				{
					this.Onnr_telefonChanging(value);
					this.SendPropertyChanging();
					this._nr_telefon = value;
					this.SendPropertyChanged("nr_telefon");
					this.Onnr_telefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fabricant_masina", Storage="_masinas", ThisKey="id", OtherKey="fk_brand")]
		public EntitySet<masina> masinas
		{
			get
			{
				return this._masinas;
			}
			set
			{
				this._masinas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_masinas(masina entity)
		{
			this.SendPropertyChanging();
			entity.fabricant = this;
		}
		
		private void detach_masinas(masina entity)
		{
			this.SendPropertyChanging();
			entity.fabricant = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.masina")]
	public partial class masina : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _vin;
		
		private string _culoare;
		
		private int _fk_tip;
		
		private int _fk_brand;
		
		private int _fk_proprietar;
		
		private EntityRef<fabricant> _fabricant;
		
		private EntityRef<proprietar> _proprietar;
		
		private EntityRef<tip> _tip;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnvinChanging(string value);
    partial void OnvinChanged();
    partial void OnculoareChanging(string value);
    partial void OnculoareChanged();
    partial void Onfk_tipChanging(int value);
    partial void Onfk_tipChanged();
    partial void Onfk_brandChanging(int value);
    partial void Onfk_brandChanged();
    partial void Onfk_proprietarChanging(int value);
    partial void Onfk_proprietarChanged();
    #endregion
		
		public masina()
		{
			this._fabricant = default(EntityRef<fabricant>);
			this._proprietar = default(EntityRef<proprietar>);
			this._tip = default(EntityRef<tip>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vin", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string vin
		{
			get
			{
				return this._vin;
			}
			set
			{
				if ((this._vin != value))
				{
					this.OnvinChanging(value);
					this.SendPropertyChanging();
					this._vin = value;
					this.SendPropertyChanged("vin");
					this.OnvinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_culoare", DbType="NChar(30)")]
		public string culoare
		{
			get
			{
				return this._culoare;
			}
			set
			{
				if ((this._culoare != value))
				{
					this.OnculoareChanging(value);
					this.SendPropertyChanging();
					this._culoare = value;
					this.SendPropertyChanged("culoare");
					this.OnculoareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_tip", DbType="Int NOT NULL")]
		public int fk_tip
		{
			get
			{
				return this._fk_tip;
			}
			set
			{
				if ((this._fk_tip != value))
				{
					if (this._tip.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_tipChanging(value);
					this.SendPropertyChanging();
					this._fk_tip = value;
					this.SendPropertyChanged("fk_tip");
					this.Onfk_tipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_brand", DbType="Int NOT NULL")]
		public int fk_brand
		{
			get
			{
				return this._fk_brand;
			}
			set
			{
				if ((this._fk_brand != value))
				{
					if (this._fabricant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_brandChanging(value);
					this.SendPropertyChanging();
					this._fk_brand = value;
					this.SendPropertyChanged("fk_brand");
					this.Onfk_brandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_proprietar", DbType="Int NOT NULL")]
		public int fk_proprietar
		{
			get
			{
				return this._fk_proprietar;
			}
			set
			{
				if ((this._fk_proprietar != value))
				{
					if (this._proprietar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_proprietarChanging(value);
					this.SendPropertyChanging();
					this._fk_proprietar = value;
					this.SendPropertyChanged("fk_proprietar");
					this.Onfk_proprietarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fabricant_masina", Storage="_fabricant", ThisKey="fk_brand", OtherKey="id", IsForeignKey=true)]
		public fabricant fabricant
		{
			get
			{
				return this._fabricant.Entity;
			}
			set
			{
				fabricant previousValue = this._fabricant.Entity;
				if (((previousValue != value) 
							|| (this._fabricant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._fabricant.Entity = null;
						previousValue.masinas.Remove(this);
					}
					this._fabricant.Entity = value;
					if ((value != null))
					{
						value.masinas.Add(this);
						this._fk_brand = value.id;
					}
					else
					{
						this._fk_brand = default(int);
					}
					this.SendPropertyChanged("fabricant");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="proprietar_masina", Storage="_proprietar", ThisKey="fk_proprietar", OtherKey="id", IsForeignKey=true)]
		public proprietar proprietar
		{
			get
			{
				return this._proprietar.Entity;
			}
			set
			{
				proprietar previousValue = this._proprietar.Entity;
				if (((previousValue != value) 
							|| (this._proprietar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._proprietar.Entity = null;
						previousValue.masinas.Remove(this);
					}
					this._proprietar.Entity = value;
					if ((value != null))
					{
						value.masinas.Add(this);
						this._fk_proprietar = value.id;
					}
					else
					{
						this._fk_proprietar = default(int);
					}
					this.SendPropertyChanged("proprietar");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tip_masina", Storage="_tip", ThisKey="fk_tip", OtherKey="id", IsForeignKey=true)]
		public tip tip
		{
			get
			{
				return this._tip.Entity;
			}
			set
			{
				tip previousValue = this._tip.Entity;
				if (((previousValue != value) 
							|| (this._tip.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tip.Entity = null;
						previousValue.masinas.Remove(this);
					}
					this._tip.Entity = value;
					if ((value != null))
					{
						value.masinas.Add(this);
						this._fk_tip = value.id;
					}
					else
					{
						this._fk_tip = default(int);
					}
					this.SendPropertyChanged("tip");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mecanic")]
	public partial class mecanic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nume;
		
		private string _prenume;
		
		private string _telefon;
		
		private System.DateTime _data_angajare;
		
		private System.Nullable<int> _fk_director;
		
		private EntitySet<brevet_dispozitiv> _brevet_dispozitivs;
		
		private EntitySet<operatie> _operaties;
		
		private EntitySet<utilizare_dispozitiv> _utilizare_dispozitivs;
		
		private EntityRef<director_tehnic> _director_tehnic;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnumeChanging(string value);
    partial void OnnumeChanged();
    partial void OnprenumeChanging(string value);
    partial void OnprenumeChanged();
    partial void OntelefonChanging(string value);
    partial void OntelefonChanged();
    partial void Ondata_angajareChanging(System.DateTime value);
    partial void Ondata_angajareChanged();
    partial void Onfk_directorChanging(System.Nullable<int> value);
    partial void Onfk_directorChanged();
    #endregion
		
		public mecanic()
		{
			this._brevet_dispozitivs = new EntitySet<brevet_dispozitiv>(new Action<brevet_dispozitiv>(this.attach_brevet_dispozitivs), new Action<brevet_dispozitiv>(this.detach_brevet_dispozitivs));
			this._operaties = new EntitySet<operatie>(new Action<operatie>(this.attach_operaties), new Action<operatie>(this.detach_operaties));
			this._utilizare_dispozitivs = new EntitySet<utilizare_dispozitiv>(new Action<utilizare_dispozitiv>(this.attach_utilizare_dispozitivs), new Action<utilizare_dispozitiv>(this.detach_utilizare_dispozitivs));
			this._director_tehnic = default(EntityRef<director_tehnic>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nume", DbType="NChar(13) NOT NULL", CanBeNull=false)]
		public string nume
		{
			get
			{
				return this._nume;
			}
			set
			{
				if ((this._nume != value))
				{
					this.OnnumeChanging(value);
					this.SendPropertyChanging();
					this._nume = value;
					this.SendPropertyChanged("nume");
					this.OnnumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenume", DbType="NChar(13) NOT NULL", CanBeNull=false)]
		public string prenume
		{
			get
			{
				return this._prenume;
			}
			set
			{
				if ((this._prenume != value))
				{
					this.OnprenumeChanging(value);
					this.SendPropertyChanging();
					this._prenume = value;
					this.SendPropertyChanged("prenume");
					this.OnprenumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="NChar(13) NOT NULL", CanBeNull=false)]
		public string telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_angajare", DbType="Date NOT NULL")]
		public System.DateTime data_angajare
		{
			get
			{
				return this._data_angajare;
			}
			set
			{
				if ((this._data_angajare != value))
				{
					this.Ondata_angajareChanging(value);
					this.SendPropertyChanging();
					this._data_angajare = value;
					this.SendPropertyChanged("data_angajare");
					this.Ondata_angajareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_director", DbType="Int")]
		public System.Nullable<int> fk_director
		{
			get
			{
				return this._fk_director;
			}
			set
			{
				if ((this._fk_director != value))
				{
					if (this._director_tehnic.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_directorChanging(value);
					this.SendPropertyChanging();
					this._fk_director = value;
					this.SendPropertyChanged("fk_director");
					this.Onfk_directorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mecanic_brevet_dispozitiv", Storage="_brevet_dispozitivs", ThisKey="id", OtherKey="fk_mecanic")]
		public EntitySet<brevet_dispozitiv> brevet_dispozitivs
		{
			get
			{
				return this._brevet_dispozitivs;
			}
			set
			{
				this._brevet_dispozitivs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mecanic_operatie", Storage="_operaties", ThisKey="id", OtherKey="fk_mecanic")]
		public EntitySet<operatie> operaties
		{
			get
			{
				return this._operaties;
			}
			set
			{
				this._operaties.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mecanic_utilizare_dispozitiv", Storage="_utilizare_dispozitivs", ThisKey="id", OtherKey="fk_mecanic")]
		public EntitySet<utilizare_dispozitiv> utilizare_dispozitivs
		{
			get
			{
				return this._utilizare_dispozitivs;
			}
			set
			{
				this._utilizare_dispozitivs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="director_tehnic_mecanic", Storage="_director_tehnic", ThisKey="fk_director", OtherKey="id", IsForeignKey=true)]
		public director_tehnic director_tehnic
		{
			get
			{
				return this._director_tehnic.Entity;
			}
			set
			{
				director_tehnic previousValue = this._director_tehnic.Entity;
				if (((previousValue != value) 
							|| (this._director_tehnic.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._director_tehnic.Entity = null;
						previousValue.mecanics.Remove(this);
					}
					this._director_tehnic.Entity = value;
					if ((value != null))
					{
						value.mecanics.Add(this);
						this._fk_director = value.id;
					}
					else
					{
						this._fk_director = default(Nullable<int>);
					}
					this.SendPropertyChanged("director_tehnic");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_brevet_dispozitivs(brevet_dispozitiv entity)
		{
			this.SendPropertyChanging();
			entity.mecanic = this;
		}
		
		private void detach_brevet_dispozitivs(brevet_dispozitiv entity)
		{
			this.SendPropertyChanging();
			entity.mecanic = null;
		}
		
		private void attach_operaties(operatie entity)
		{
			this.SendPropertyChanging();
			entity.mecanic = this;
		}
		
		private void detach_operaties(operatie entity)
		{
			this.SendPropertyChanging();
			entity.mecanic = null;
		}
		
		private void attach_utilizare_dispozitivs(utilizare_dispozitiv entity)
		{
			this.SendPropertyChanging();
			entity.mecanic = this;
		}
		
		private void detach_utilizare_dispozitivs(utilizare_dispozitiv entity)
		{
			this.SendPropertyChanging();
			entity.mecanic = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.operatie")]
	public partial class operatie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _fk_reparatie;
		
		private int _fk_mecanic;
		
		private EntityRef<mecanic> _mecanic;
		
		private EntityRef<reparatie> _reparatie;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onfk_reparatieChanging(int value);
    partial void Onfk_reparatieChanged();
    partial void Onfk_mecanicChanging(int value);
    partial void Onfk_mecanicChanged();
    #endregion
		
		public operatie()
		{
			this._mecanic = default(EntityRef<mecanic>);
			this._reparatie = default(EntityRef<reparatie>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_reparatie", DbType="Int NOT NULL")]
		public int fk_reparatie
		{
			get
			{
				return this._fk_reparatie;
			}
			set
			{
				if ((this._fk_reparatie != value))
				{
					if (this._reparatie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_reparatieChanging(value);
					this.SendPropertyChanging();
					this._fk_reparatie = value;
					this.SendPropertyChanged("fk_reparatie");
					this.Onfk_reparatieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_mecanic", DbType="Int NOT NULL")]
		public int fk_mecanic
		{
			get
			{
				return this._fk_mecanic;
			}
			set
			{
				if ((this._fk_mecanic != value))
				{
					if (this._mecanic.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_mecanicChanging(value);
					this.SendPropertyChanging();
					this._fk_mecanic = value;
					this.SendPropertyChanged("fk_mecanic");
					this.Onfk_mecanicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mecanic_operatie", Storage="_mecanic", ThisKey="fk_mecanic", OtherKey="id", IsForeignKey=true)]
		public mecanic mecanic
		{
			get
			{
				return this._mecanic.Entity;
			}
			set
			{
				mecanic previousValue = this._mecanic.Entity;
				if (((previousValue != value) 
							|| (this._mecanic.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mecanic.Entity = null;
						previousValue.operaties.Remove(this);
					}
					this._mecanic.Entity = value;
					if ((value != null))
					{
						value.operaties.Add(this);
						this._fk_mecanic = value.id;
					}
					else
					{
						this._fk_mecanic = default(int);
					}
					this.SendPropertyChanged("mecanic");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reparatie_operatie", Storage="_reparatie", ThisKey="fk_reparatie", OtherKey="id", IsForeignKey=true)]
		public reparatie reparatie
		{
			get
			{
				return this._reparatie.Entity;
			}
			set
			{
				reparatie previousValue = this._reparatie.Entity;
				if (((previousValue != value) 
							|| (this._reparatie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._reparatie.Entity = null;
						previousValue.operaties.Remove(this);
					}
					this._reparatie.Entity = value;
					if ((value != null))
					{
						value.operaties.Add(this);
						this._fk_reparatie = value.id;
					}
					else
					{
						this._fk_reparatie = default(int);
					}
					this.SendPropertyChanged("reparatie");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.piesa")]
	public partial class piesa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nume;
		
		private int _fk_reparatie;
		
		private int _cantitate;
		
		private int _fk_supplier;
		
		private EntityRef<reparatie> _reparatie;
		
		private EntityRef<supplier> _supplier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnumeChanging(string value);
    partial void OnnumeChanged();
    partial void Onfk_reparatieChanging(int value);
    partial void Onfk_reparatieChanged();
    partial void OncantitateChanging(int value);
    partial void OncantitateChanged();
    partial void Onfk_supplierChanging(int value);
    partial void Onfk_supplierChanged();
    #endregion
		
		public piesa()
		{
			this._reparatie = default(EntityRef<reparatie>);
			this._supplier = default(EntityRef<supplier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nume", DbType="NChar(90) NOT NULL", CanBeNull=false)]
		public string nume
		{
			get
			{
				return this._nume;
			}
			set
			{
				if ((this._nume != value))
				{
					this.OnnumeChanging(value);
					this.SendPropertyChanging();
					this._nume = value;
					this.SendPropertyChanged("nume");
					this.OnnumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_reparatie", DbType="Int NOT NULL")]
		public int fk_reparatie
		{
			get
			{
				return this._fk_reparatie;
			}
			set
			{
				if ((this._fk_reparatie != value))
				{
					if (this._reparatie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_reparatieChanging(value);
					this.SendPropertyChanging();
					this._fk_reparatie = value;
					this.SendPropertyChanged("fk_reparatie");
					this.Onfk_reparatieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantitate", DbType="Int NOT NULL")]
		public int cantitate
		{
			get
			{
				return this._cantitate;
			}
			set
			{
				if ((this._cantitate != value))
				{
					this.OncantitateChanging(value);
					this.SendPropertyChanging();
					this._cantitate = value;
					this.SendPropertyChanged("cantitate");
					this.OncantitateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_supplier", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int fk_supplier
		{
			get
			{
				return this._fk_supplier;
			}
			set
			{
				if ((this._fk_supplier != value))
				{
					if (this._supplier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_supplierChanging(value);
					this.SendPropertyChanging();
					this._fk_supplier = value;
					this.SendPropertyChanged("fk_supplier");
					this.Onfk_supplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reparatie_piesa", Storage="_reparatie", ThisKey="fk_reparatie", OtherKey="id", IsForeignKey=true)]
		public reparatie reparatie
		{
			get
			{
				return this._reparatie.Entity;
			}
			set
			{
				reparatie previousValue = this._reparatie.Entity;
				if (((previousValue != value) 
							|| (this._reparatie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._reparatie.Entity = null;
						previousValue.piesas.Remove(this);
					}
					this._reparatie.Entity = value;
					if ((value != null))
					{
						value.piesas.Add(this);
						this._fk_reparatie = value.id;
					}
					else
					{
						this._fk_reparatie = default(int);
					}
					this.SendPropertyChanged("reparatie");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="supplier_piesa", Storage="_supplier", ThisKey="fk_supplier", OtherKey="id", IsForeignKey=true)]
		public supplier supplier
		{
			get
			{
				return this._supplier.Entity;
			}
			set
			{
				supplier previousValue = this._supplier.Entity;
				if (((previousValue != value) 
							|| (this._supplier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._supplier.Entity = null;
						previousValue.piesas.Remove(this);
					}
					this._supplier.Entity = value;
					if ((value != null))
					{
						value.piesas.Add(this);
						this._fk_supplier = value.id;
					}
					else
					{
						this._fk_supplier = default(int);
					}
					this.SendPropertyChanged("supplier");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.proprietar")]
	public partial class proprietar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nume;
		
		private string _prenume;
		
		private string _telefon;
		
		private string _nrcard;
		
		private EntitySet<masina> _masinas;
		
		private EntitySet<vanzare> _vanzares;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnumeChanging(string value);
    partial void OnnumeChanged();
    partial void OnprenumeChanging(string value);
    partial void OnprenumeChanged();
    partial void OntelefonChanging(string value);
    partial void OntelefonChanged();
    partial void OnnrcardChanging(string value);
    partial void OnnrcardChanged();
    #endregion
		
		public proprietar()
		{
			this._masinas = new EntitySet<masina>(new Action<masina>(this.attach_masinas), new Action<masina>(this.detach_masinas));
			this._vanzares = new EntitySet<vanzare>(new Action<vanzare>(this.attach_vanzares), new Action<vanzare>(this.detach_vanzares));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nume", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string nume
		{
			get
			{
				return this._nume;
			}
			set
			{
				if ((this._nume != value))
				{
					this.OnnumeChanging(value);
					this.SendPropertyChanging();
					this._nume = value;
					this.SendPropertyChanged("nume");
					this.OnnumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenume", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string prenume
		{
			get
			{
				return this._prenume;
			}
			set
			{
				if ((this._prenume != value))
				{
					this.OnprenumeChanging(value);
					this.SendPropertyChanging();
					this._prenume = value;
					this.SendPropertyChanged("prenume");
					this.OnprenumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrcard", DbType="NChar(20)")]
		public string nrcard
		{
			get
			{
				return this._nrcard;
			}
			set
			{
				if ((this._nrcard != value))
				{
					this.OnnrcardChanging(value);
					this.SendPropertyChanging();
					this._nrcard = value;
					this.SendPropertyChanged("nrcard");
					this.OnnrcardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="proprietar_masina", Storage="_masinas", ThisKey="id", OtherKey="fk_proprietar")]
		public EntitySet<masina> masinas
		{
			get
			{
				return this._masinas;
			}
			set
			{
				this._masinas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="proprietar_vanzare", Storage="_vanzares", ThisKey="id", OtherKey="fk_proprietar")]
		public EntitySet<vanzare> vanzares
		{
			get
			{
				return this._vanzares;
			}
			set
			{
				this._vanzares.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_masinas(masina entity)
		{
			this.SendPropertyChanging();
			entity.proprietar = this;
		}
		
		private void detach_masinas(masina entity)
		{
			this.SendPropertyChanging();
			entity.proprietar = null;
		}
		
		private void attach_vanzares(vanzare entity)
		{
			this.SendPropertyChanging();
			entity.proprietar = this;
		}
		
		private void detach_vanzares(vanzare entity)
		{
			this.SendPropertyChanging();
			entity.proprietar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.reparatie")]
	public partial class reparatie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _fk_masina;
		
		private EntitySet<operatie> _operaties;
		
		private EntitySet<piesa> _piesas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onfk_masinaChanging(int value);
    partial void Onfk_masinaChanged();
    #endregion
		
		public reparatie()
		{
			this._operaties = new EntitySet<operatie>(new Action<operatie>(this.attach_operaties), new Action<operatie>(this.detach_operaties));
			this._piesas = new EntitySet<piesa>(new Action<piesa>(this.attach_piesas), new Action<piesa>(this.detach_piesas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_masina", DbType="Int NOT NULL")]
		public int fk_masina
		{
			get
			{
				return this._fk_masina;
			}
			set
			{
				if ((this._fk_masina != value))
				{
					this.Onfk_masinaChanging(value);
					this.SendPropertyChanging();
					this._fk_masina = value;
					this.SendPropertyChanged("fk_masina");
					this.Onfk_masinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reparatie_operatie", Storage="_operaties", ThisKey="id", OtherKey="fk_reparatie")]
		public EntitySet<operatie> operaties
		{
			get
			{
				return this._operaties;
			}
			set
			{
				this._operaties.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reparatie_piesa", Storage="_piesas", ThisKey="id", OtherKey="fk_reparatie")]
		public EntitySet<piesa> piesas
		{
			get
			{
				return this._piesas;
			}
			set
			{
				this._piesas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_operaties(operatie entity)
		{
			this.SendPropertyChanging();
			entity.reparatie = this;
		}
		
		private void detach_operaties(operatie entity)
		{
			this.SendPropertyChanging();
			entity.reparatie = null;
		}
		
		private void attach_piesas(piesa entity)
		{
			this.SendPropertyChanging();
			entity.reparatie = this;
		}
		
		private void detach_piesas(piesa entity)
		{
			this.SendPropertyChanging();
			entity.reparatie = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.supplier")]
	public partial class supplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nume;
		
		private string _telefon;
		
		private EntitySet<piesa> _piesas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnumeChanging(string value);
    partial void OnnumeChanged();
    partial void OntelefonChanging(string value);
    partial void OntelefonChanged();
    #endregion
		
		public supplier()
		{
			this._piesas = new EntitySet<piesa>(new Action<piesa>(this.attach_piesas), new Action<piesa>(this.detach_piesas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nume", DbType="NChar(40)")]
		public string nume
		{
			get
			{
				return this._nume;
			}
			set
			{
				if ((this._nume != value))
				{
					this.OnnumeChanging(value);
					this.SendPropertyChanging();
					this._nume = value;
					this.SendPropertyChanged("nume");
					this.OnnumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="NChar(40)")]
		public string telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="supplier_piesa", Storage="_piesas", ThisKey="id", OtherKey="fk_supplier")]
		public EntitySet<piesa> piesas
		{
			get
			{
				return this._piesas;
			}
			set
			{
				this._piesas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_piesas(piesa entity)
		{
			this.SendPropertyChanging();
			entity.supplier = this;
		}
		
		private void detach_piesas(piesa entity)
		{
			this.SendPropertyChanging();
			entity.supplier = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tip")]
	public partial class tip : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nume;
		
		private EntitySet<masina> _masinas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnumeChanging(string value);
    partial void OnnumeChanged();
    #endregion
		
		public tip()
		{
			this._masinas = new EntitySet<masina>(new Action<masina>(this.attach_masinas), new Action<masina>(this.detach_masinas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nume", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string nume
		{
			get
			{
				return this._nume;
			}
			set
			{
				if ((this._nume != value))
				{
					this.OnnumeChanging(value);
					this.SendPropertyChanging();
					this._nume = value;
					this.SendPropertyChanged("nume");
					this.OnnumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tip_masina", Storage="_masinas", ThisKey="id", OtherKey="fk_tip")]
		public EntitySet<masina> masinas
		{
			get
			{
				return this._masinas;
			}
			set
			{
				this._masinas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_masinas(masina entity)
		{
			this.SendPropertyChanging();
			entity.tip = this;
		}
		
		private void detach_masinas(masina entity)
		{
			this.SendPropertyChanging();
			entity.tip = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tip_brevet")]
	public partial class tip_brevet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _tip;
		
		private EntitySet<brevet_dispozitiv> _brevet_dispozitivs;
		
		private EntitySet<dispozitiv> _dispozitivs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntipChanging(string value);
    partial void OntipChanged();
    #endregion
		
		public tip_brevet()
		{
			this._brevet_dispozitivs = new EntitySet<brevet_dispozitiv>(new Action<brevet_dispozitiv>(this.attach_brevet_dispozitivs), new Action<brevet_dispozitiv>(this.detach_brevet_dispozitivs));
			this._dispozitivs = new EntitySet<dispozitiv>(new Action<dispozitiv>(this.attach_dispozitivs), new Action<dispozitiv>(this.detach_dispozitivs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tip", DbType="NChar(30)")]
		public string tip
		{
			get
			{
				return this._tip;
			}
			set
			{
				if ((this._tip != value))
				{
					this.OntipChanging(value);
					this.SendPropertyChanging();
					this._tip = value;
					this.SendPropertyChanged("tip");
					this.OntipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tip_brevet_brevet_dispozitiv", Storage="_brevet_dispozitivs", ThisKey="id", OtherKey="tipbrevet")]
		public EntitySet<brevet_dispozitiv> brevet_dispozitivs
		{
			get
			{
				return this._brevet_dispozitivs;
			}
			set
			{
				this._brevet_dispozitivs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tip_brevet_dispozitiv", Storage="_dispozitivs", ThisKey="id", OtherKey="brevet_necesar")]
		public EntitySet<dispozitiv> dispozitivs
		{
			get
			{
				return this._dispozitivs;
			}
			set
			{
				this._dispozitivs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_brevet_dispozitivs(brevet_dispozitiv entity)
		{
			this.SendPropertyChanging();
			entity.tip_brevet = this;
		}
		
		private void detach_brevet_dispozitivs(brevet_dispozitiv entity)
		{
			this.SendPropertyChanging();
			entity.tip_brevet = null;
		}
		
		private void attach_dispozitivs(dispozitiv entity)
		{
			this.SendPropertyChanging();
			entity.tip_brevet = this;
		}
		
		private void detach_dispozitivs(dispozitiv entity)
		{
			this.SendPropertyChanging();
			entity.tip_brevet = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.utilizare_dispozitiv")]
	public partial class utilizare_dispozitiv : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _fk_mecanic;
		
		private int _fk_dispozitiv;
		
		private System.DateTime _data;
		
		private EntityRef<dispozitiv> _dispozitiv;
		
		private EntityRef<mecanic> _mecanic;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onfk_mecanicChanging(int value);
    partial void Onfk_mecanicChanged();
    partial void Onfk_dispozitivChanging(int value);
    partial void Onfk_dispozitivChanged();
    partial void OndataChanging(System.DateTime value);
    partial void OndataChanged();
    #endregion
		
		public utilizare_dispozitiv()
		{
			this._dispozitiv = default(EntityRef<dispozitiv>);
			this._mecanic = default(EntityRef<mecanic>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_mecanic", DbType="Int NOT NULL")]
		public int fk_mecanic
		{
			get
			{
				return this._fk_mecanic;
			}
			set
			{
				if ((this._fk_mecanic != value))
				{
					if (this._mecanic.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_mecanicChanging(value);
					this.SendPropertyChanging();
					this._fk_mecanic = value;
					this.SendPropertyChanged("fk_mecanic");
					this.Onfk_mecanicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_dispozitiv", DbType="Int NOT NULL")]
		public int fk_dispozitiv
		{
			get
			{
				return this._fk_dispozitiv;
			}
			set
			{
				if ((this._fk_dispozitiv != value))
				{
					if (this._dispozitiv.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_dispozitivChanging(value);
					this.SendPropertyChanging();
					this._fk_dispozitiv = value;
					this.SendPropertyChanged("fk_dispozitiv");
					this.Onfk_dispozitivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="Date NOT NULL")]
		public System.DateTime data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dispozitiv_utilizare_dispozitiv", Storage="_dispozitiv", ThisKey="fk_dispozitiv", OtherKey="id", IsForeignKey=true)]
		public dispozitiv dispozitiv
		{
			get
			{
				return this._dispozitiv.Entity;
			}
			set
			{
				dispozitiv previousValue = this._dispozitiv.Entity;
				if (((previousValue != value) 
							|| (this._dispozitiv.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dispozitiv.Entity = null;
						previousValue.utilizare_dispozitivs.Remove(this);
					}
					this._dispozitiv.Entity = value;
					if ((value != null))
					{
						value.utilizare_dispozitivs.Add(this);
						this._fk_dispozitiv = value.id;
					}
					else
					{
						this._fk_dispozitiv = default(int);
					}
					this.SendPropertyChanged("dispozitiv");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mecanic_utilizare_dispozitiv", Storage="_mecanic", ThisKey="fk_mecanic", OtherKey="id", IsForeignKey=true)]
		public mecanic mecanic
		{
			get
			{
				return this._mecanic.Entity;
			}
			set
			{
				mecanic previousValue = this._mecanic.Entity;
				if (((previousValue != value) 
							|| (this._mecanic.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mecanic.Entity = null;
						previousValue.utilizare_dispozitivs.Remove(this);
					}
					this._mecanic.Entity = value;
					if ((value != null))
					{
						value.utilizare_dispozitivs.Add(this);
						this._fk_mecanic = value.id;
					}
					else
					{
						this._fk_mecanic = default(int);
					}
					this.SendPropertyChanged("mecanic");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vanzare")]
	public partial class vanzare : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _fk_angajat;
		
		private int _fk_proprietar;
		
		private int _fk_piesa;
		
		private System.Nullable<int> _amount;
		
		private EntityRef<vanzator> _vanzator;
		
		private EntityRef<proprietar> _proprietar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onfk_angajatChanging(int value);
    partial void Onfk_angajatChanged();
    partial void Onfk_proprietarChanging(int value);
    partial void Onfk_proprietarChanged();
    partial void Onfk_piesaChanging(int value);
    partial void Onfk_piesaChanged();
    partial void OnamountChanging(System.Nullable<int> value);
    partial void OnamountChanged();
    #endregion
		
		public vanzare()
		{
			this._vanzator = default(EntityRef<vanzator>);
			this._proprietar = default(EntityRef<proprietar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_angajat", DbType="Int NOT NULL")]
		public int fk_angajat
		{
			get
			{
				return this._fk_angajat;
			}
			set
			{
				if ((this._fk_angajat != value))
				{
					if (this._vanzator.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_angajatChanging(value);
					this.SendPropertyChanging();
					this._fk_angajat = value;
					this.SendPropertyChanged("fk_angajat");
					this.Onfk_angajatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_proprietar", DbType="Int NOT NULL")]
		public int fk_proprietar
		{
			get
			{
				return this._fk_proprietar;
			}
			set
			{
				if ((this._fk_proprietar != value))
				{
					if (this._proprietar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_proprietarChanging(value);
					this.SendPropertyChanging();
					this._fk_proprietar = value;
					this.SendPropertyChanged("fk_proprietar");
					this.Onfk_proprietarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_piesa", DbType="Int NOT NULL")]
		public int fk_piesa
		{
			get
			{
				return this._fk_piesa;
			}
			set
			{
				if ((this._fk_piesa != value))
				{
					this.Onfk_piesaChanging(value);
					this.SendPropertyChanging();
					this._fk_piesa = value;
					this.SendPropertyChanged("fk_piesa");
					this.Onfk_piesaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Int")]
		public System.Nullable<int> amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this.OnamountChanging(value);
					this.SendPropertyChanging();
					this._amount = value;
					this.SendPropertyChanged("amount");
					this.OnamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vanzator_vanzare", Storage="_vanzator", ThisKey="fk_angajat", OtherKey="id", IsForeignKey=true)]
		public vanzator vanzator
		{
			get
			{
				return this._vanzator.Entity;
			}
			set
			{
				vanzator previousValue = this._vanzator.Entity;
				if (((previousValue != value) 
							|| (this._vanzator.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._vanzator.Entity = null;
						previousValue.vanzares.Remove(this);
					}
					this._vanzator.Entity = value;
					if ((value != null))
					{
						value.vanzares.Add(this);
						this._fk_angajat = value.id;
					}
					else
					{
						this._fk_angajat = default(int);
					}
					this.SendPropertyChanged("vanzator");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="proprietar_vanzare", Storage="_proprietar", ThisKey="fk_proprietar", OtherKey="id", IsForeignKey=true)]
		public proprietar proprietar
		{
			get
			{
				return this._proprietar.Entity;
			}
			set
			{
				proprietar previousValue = this._proprietar.Entity;
				if (((previousValue != value) 
							|| (this._proprietar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._proprietar.Entity = null;
						previousValue.vanzares.Remove(this);
					}
					this._proprietar.Entity = value;
					if ((value != null))
					{
						value.vanzares.Add(this);
						this._fk_proprietar = value.id;
					}
					else
					{
						this._fk_proprietar = default(int);
					}
					this.SendPropertyChanged("proprietar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
